---
title: "EDUC 263: Data Management and Manipulation in R"
subtitle: "Software to install before first class meeting"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
***
#### Please skim through all of the instructions before getting start.  


## 1. Create a GitHub account  
  * We will be conducting all class-related discussion on this version control system instead of using CCLE.  
  *  Follow this [link](https://github.com/ozanj/rclass/raw/master/todo/git_instructions.pdf) for instructions on creating a GitHub account and installing Git on your local computer.
  
## 2. Install R 
  * Go to https://cran.r-project.org/  
  * Select "Download R for Windows"  
  
      * Click "install R for the first time"
      * Click "Download R 4.0.2 for Windows"  
  * Select "Download R for (Mac) OS  X"   
  
      * Click "R-4.0.2.pkg"   
        
## 3. Install RStudio  
  * Go to https://www.rstudio.com/products/rstudio/download/  
  * Scroll to the bottom of the page  
  * Select "RStudio-1.3.1056.exe - Windows 10/8/7" for Windows users  
  * Select "RStudio-1.3.1056.dmg - macOS 10.13+ (64-bit)" for Mac users  
    
## 4. Create R Markdown file that “knits” HTML document in RStudio  
  * What do we mean by this?  
  
    * We will use R Markdown for lectures and turning in problem sets (homeworks).  
    * R Markdown allows us to create documents in a variety of formats (HTML, pdf, word, etc.). For example, this document was created using R markdown (pdf).  
    * [Here](https://rmarkdown.rstudio.com/formats.html) is a link to more information on R Markdown outputs.  
  * Steps to follow to create R Markdown file that knits HTML document  
    * Load RStudio  
    * At the top left corner select “File” ->“New file” -> “R Markdown”  
    * Select “HTML”, title your markdown file (optional), and click “OK”  
    * Now select the “Knit” tab (icon with blue yarn ball) or scroll down and “Knit to HTML”  
    * Give your file a name and save (can delete later) in place that is easy to locate (Desktop, Downloads, etc.)  
    * You should have a saved HTML file (extension .HTML) and an R markdown file (extension .Rmd)  
    
## 5. Complete the first chapter of Introduction to R on Datacamp [here](https://learn.datacamp.com/courses/free-introduction-to-r)  

  * _Note: All first chapters of DataCamp's standard courses are free._   
  
      * Follow the link and create an account  
      * This tutorial may take 2-4 hours  
      * We encourage you all to complete this tutorial and run code on your own RStudio to get some practice.  
  
## 6. Watch videos on relative and absolute filepaths  

  * Absolute versus relative file paths [Youtube link](https://www.youtube.com/watch?v=ephId3mYu9o)  
  * Relative paths and working directory in R [Youtube link](https://www.youtube.com/watch?v=fe6GA200dks)  
  
## 7. Install tinytex  

  * Why are we asking you to do this?  
    * You will need to install LaTeX (lah-tech or lay-tech) on your computer to create pdf documents in R Markdown.  
    * You do not need to know how to use LaTeX. LaTeX is used in the background to compile pdf documents for you.  
    * [Here](https://medium.com/@sorenlind/create-pdf-reports-using-r-r-markdown-latex-and-knitr-on-macos-high-sierra-e7b5705c9fd) is a helpful article on creating PDf reports using R, R Markdown, LaTeX, and knitr.
  * We **strongly recommend** installing **tinytex** in RStudio because it is smaller in size and it only installs LaTeX packages you need. **However, if you have MikTeX/MacTeX already installed** on your computer or you plan to use LaTeX in other courses we recommend you update to the most current version of MikTeX/MacTeX.  
    * __Please note that you only need to install one!__ You may run into some issues if you try to install tinytex and you already have MikTeX/MacTeX installed so please stick to only one.  
    
  * Instructions for installing tinytex  
  
    [Here](https://yihui.name/tinytex/) is a helpful link to install tinytex  
    
    1. Open up RStudio  
    2. In the "console" paste the following and hit return(enter): __install.packages('tinytex')__  
      + _Do not worry about the code right now. We will review how to install packages in the following weeks._ 
    3. Once the package is installed, paste the following code in the "console" and hit return(enter): __tinytex::install_tinytex()__  
    
  * [Instructions](https://github.com/ozanj/rclass/raw/master/todo/miktex-mactex_instructions.pdf) for installing MikTeX/MacTeX 
  
    * We understand that installing MikTeX/MacTeX can be challenging and time-consuming and
for that reason, we recommend installing tinytex if you do not already have MikTeX/MacTeX installed. We ask you to come to class with all the software installed. Please reach out to me if you are running into problems. I am happy to help. 

 
## 8. Create R Markdown file that “knits” PDF document in RStudio  

  * Why are we asking you to do this?  
  
    * We will ask you to submit problem sets (homeworks) as pdf documents.  
  * Steps to follow to create R Markdown file that knits PDF document  
  
    * Once tinytex or MikTeX/MacTeX are installed, return to RStudio  
    * At the top left corner select “File” -> “New file” -> “R Markdown”  
    * Select “PDF”, title your markdown file (optional), and click “OK”  
    * Now select the “Knit” tab (icon with blue yarn ball) or scroll down and “Knit to PDF”  
    * Give your file a name and save (can delete later) in place that is easy to locate  
    * You should have a saved pdf file (extension .pdf) and an R markdown file (extension .Rmd)  
    
    *If you receive an error shoot me an email and we can troubleshoot together*

## 9. Create R Markdown file that “knits” (PDF) beamer presentation in RStudio  

  * Why are we asking you to do this?  
  
    * Beamer is essentially a pdf presentation created by LaTeX.  
    * Lectures will be in beamer format and we want you to be able to run lecture slides on your own.  
    * Once tinytex or MikTeX/MacTeX are installed, create R Markdown file that knits to (PDf) beamer presentation.  
  * Steps to follow to create R Markdown file that knits beamer presentation  
  
    * Return to RStudio  
    * At the top left corner select “File” -> “New file” -> “R Mardown”  
    * Select “Presentation” on the left table, then “(PDF) Beamer”, and click “OK”  
    * Now select the “Knit” tab (icon with blue yarn ball) or scroll down and “Knit to PDF (Beamer)”  
    * Give your file a name and save (can delete later) in place that is easy to locate  
    * You should have a saved pdf file (extension .pdf) and an R markdown file (extension .Rmd)  
    
    *If you were unable to knit to pdf in the step above, this may not work for you. If you receive an error shoot me an email and we can troubleshoot together*   
    
\  
\  
  

*Disclaimer: I am a Mac user and will do the best I can assisting with any Windows issues*
